name: supplications_from_quran
description: Supplications from Quran

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  path_provider: ^2.0.11
  path: ^1.8.2
  sqflite: ^2.1.0
  flutter_html: ^2.2.1
  share_plus: ^4.4.0
  clipboard: ^0.1.3
  scrollable_positioned_list: ^0.3.4
  provider: ^6.0.3
  flutter_colorpicker: ^1.0.3
  smooth_page_indicator: ^1.0.0+2
  just_audio: ^0.9.29
  screenshot: ^1.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
  - assets/databases/
  - assets/audios/
  - assets/pictures/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf
    - family: Quran
      fonts:
        - asset: assets/fonts/quran_font.ttf
